# Generated by Django 3.1.2 on 2020-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('healthy', models.IntegerField()),
                ('sick', models.IntegerField()),
            ],
        ),
    ]
